### ISSUE TITLE
カレンダー絵文字版

### ISSUE THREAD

**Issue by oyasiraz** [labocho/weathercal#1]
素敵な方法提供を有り難うございます｡
ただ、私の地域が掲載されていないのでリクエストさせて下さい。
神戸管区気象台の神戸を追加していただければ幸甚です｡

よろしくお願い致します｡

**Comment by labocho** [comment]
ご要望ありがとうございます！
神戸をはじめ全国 73 箇所に対象地域を拡大しました。
ぜひご利用ください。
